# application.yml

# spring.application.name = ${APP_NAME:unnamed}

# spring.datasourse.url = jdbc:hsqldb:file:testdb
# spring.datasourse.username = sa
# spring.datasource.password=
# spring.datasource.dirver-class-name=org.hsqldb.jdbc.JDBCDriver

# spring.datasource.hikari.auto-commit=false
# spring.datasource.hikari.connection-timeout=3000
# spring.datasource.hikari.validation-timeout=3000
# spring.datasource.hikari.max-lifetime=60000
# spring.datasource.hikari.maximum-pool-size=20
# spring.datasource.hikari.minimum-idle=1

# properties --> yml   

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name:  com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

pebble:
  prefix: /templates/
  suffix: .html
  content-type: text/html
  encodig: UTF-8
  

#pebble.prefix=/templates/
#pebble.suffix=.pebble
#pebble.content-type=text/html
#pebble.cache=true
#pebble.encoding=UTF-8
#pebble.defaultLocale=null
#pebble.strictVariables=false


# MyBatis配置
mybatis:
  type-aliases-package: com.oldou.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true